#
# Credo is a static code analysis tool for the Elixir language with a focus on teaching and code consistency.
# https://github.com/rrrene/credo
#
# To use this workflow, you must have GitHub Advanced Security (GHAS) enabled for your repository.
#
# Instructions:
# 2. Follow the annotated workflow below and make any necessary modifications then save the workflow to your repository
#    and review the "Security" tab once the action has run.

name: Credo

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: [24.2]
        elixir: [1.14.0]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: get dependencies 
        run: mix deps.get
      - name: compile dependencies
        run: mix deps.compile
      - name: compile
        run: mix compile
      - name: credo-scan
        continue-on-error: true
        run: mix credo --format=sarif > credo_output.sarif
      - name: upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: credo_output.sarif

