name: Credo Security Scan

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Thursday at 15:45 UTC.
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  credo-security-scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        otp: [21.3, 22.3, 23.3, 24.2]
        elixir: [1.10.4, 1.11.4, 1.12.2, 1.13.4, 1.14.0]
        exclude:
          - otp: 24.2
            elixir: 1.10.4
          - otp: 21.3
            elixir: 1.12.2
          - otp: 21.3
            elixir: 1.13.4
          - otp: 21.3
            elixir: 1.14.0
          - otp: 22.3
            elixir: 1.14.0
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix credo --format=sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
